version: '3.9'

services:
  api:
    image: 'aybu-alumni-api:latest'
    container_name: aybu-alumni-api
    build:
      context: ./api-java
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4024:4024"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres:14.2-alpine
    container_name: posgresqldb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=aybualumni
      - POSTGRES_PASSWORD=aybualumni
      - POSTGRES_DB=aybualumni
#  ui:
#    image: 'aybu-alumni-ui:latest'
#    container_name: aybu-alumni-ui
#    build:
#      context: .
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    ports:
#      - "4025:4025" #güncelleriz