INSERT INTO job_titles (name) VALUES ('Software Developer') ON CONFLICT DO NOTHING;
INSERT INTO job_titles (name) VALUES ('Full-Stack Developer') ON CONFLICT DO NOTHING;
INSERT INTO job_titles (name) VALUES ('Frontend Developer') ON CONFLICT DO NOTHING;
INSERT INTO job_titles (name) VALUES ('Backend Developer') ON CONFLICT DO NOTHING;
INSERT INTO job_titles (name) VALUES ('Java Developer') ON CONFLICT DO NOTHING;
INSERT INTO job_titles (name) VALUES ('React Developer') ON CONFLICT DO NOTHING;
INSERT INTO job_titles (name) VALUES ('Database Engineer') ON CONFLICT DO NOTHING;
INSERT INTO job_titles (name) VALUES ('Game Developer') ON CONFLICT DO NOTHING;

INSERT INTO job_skills (name) VALUES ('Java') ON CONFLICT DO NOTHING;
INSERT INTO job_skills (name) VALUES ('Java 17') ON CONFLICT DO NOTHING;
INSERT INTO job_skills (name) VALUES ('OOP') ON CONFLICT DO NOTHING;
INSERT INTO job_skills (name) VALUES ('PostgreSQL') ON CONFLICT DO NOTHING;
INSERT INTO job_skills (name) VALUES ('SQL') ON CONFLICT DO NOTHING;
INSERT INTO job_skills (name) VALUES ('React') ON CONFLICT DO NOTHING;
INSERT INTO job_skills (name) VALUES ('Redux') ON CONFLICT DO NOTHING;
INSERT INTO job_skills (name) VALUES ('Unity') ON CONFLICT DO NOTHING;
INSERT INTO job_skills (name) VALUES ('HTML') ON CONFLICT DO NOTHING;
INSERT INTO job_skills (name) VALUES ('CSS') ON CONFLICT DO NOTHING;
INSERT INTO job_skills (name) VALUES ('JavaScript') ON CONFLICT DO NOTHING;
INSERT INTO job_skills (name) VALUES ('TypeScript') ON CONFLICT DO NOTHING;
INSERT INTO job_skills (name) VALUES ('Spring Boot Framework') ON CONFLICT DO NOTHING;
INSERT INTO job_skills (name) VALUES ('Amazon Web Services') ON CONFLICT DO NOTHING;
INSERT INTO job_skills (name) VALUES ('AWS S3 Storage') ON CONFLICT DO NOTHING;
